[package]
name = "bevy_bundlication"
version = "0.0.1"
license = "MIT OR Apache-2.0"
description = "Network replication for bevy based on a bundle pattern"
readme = "README.md"
repository = "https://github.com/NiseVoid/bevy_bundlication"
keywords = [
  "bevy",
  "networking",
  "server-authoritative",
  "replication",
]
categories = ["game-development", "network-programming"]
exclude = ["benches/*", "tests/*"]

edition = "2021"

[dependencies]
bevy_bundlication_macros = {version = "0.0.1", path = "macros"}

bevy = {version = "0.12", default_features=false}
renet = {version = "0.0.13", default-features=false, features = [ "bevy" ], optional = true}

bincode = "1.3"
serde = "1.0"

[features]
default = []
test = []
renet = ["dep:renet"]

[dev-dependencies]
bevy_bundlication = { path = ".", default-features = false, features = ["test"] }

[patch.crates-io]
renet = { git = "https://github.com/lucaspoffo/renet" }
